site_name: Peyton Smith
site_url: ""
use_directory_urls: false

theme:
  name: material
  nav_style: dark
  palette:
    scheme: custom
  features:
    - navigation.tabs
extra_css:
  - stylesheets/extra.css

# Page tree
nav:
#  - 'Peyton Smith Site'
  - About me: index.md
  - Experience: experience.md
  - Projects:
    - Twitter Sentiment Analysis: projects/twitter_sentiment_analysis.ipynb
    - Dumbo: projects/dumbo_xiangqi_ai.md
    - Single Cycle Processor: projects/single_cycle_processor.md
    - Object Detection: projects/em_algorithm.md
    - Eternal Flame: projects/eternal_flame_simulation.md
  - Blog: 
    - Blog Post 1: blog/mkdocs_github_actions.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde



