site_name: Peyton's mkdocs

theme:
  name: material
  pallete:
    primary: blue
    accent: blue
  features:
    - navigation.tabs

# Page tree
nav:
#  - 'Peyton's Mkdocs 1.0'
  - Home: index.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde


