site_name: Peyton Smith

theme:
  name: material
  logo: assets/black_logo.png
  font: 
    text: Arial
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette: 
    # Palette toggle for light mode
    - scheme: l_mode
      logo: assets/black_logo.png
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: d_mode
      logo: assets/white_logo.png
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    
extra_css:
- stylesheets/extra.css

# Page tree
nav:
#  - 'Peyton Smith Site'
  - Home: index.md
  - Experience: 
    - Lockheed Martin: experience/lm.md
    - AKW Ventures LLC: experience/akw_ventures.md
    - SEC Directed Internship: experience/sec_directed_internship.md
    - Aggie Sat Lab: experience/aggie_sat_lab.md
  - Projects:
    - Twitter Sentiment Analysis: projects/twitter_sentiment_analysis.ipynb
    - Image Object Detection: projects/em_algorithm.md
    - Kalman Filter: projects/kalman_filter_state_estimate_.ipynb
    - AI player for Xiangqi: projects/dumbo_xiangqi_ai.md
    - Multi Echo and Feedback Comb Filter: projects/multiecho_and_feedback_comb_filter.ipynb
    - Eternal Flame: projects/eternal_flame_simulation.md
  - Notes: 
    - Kalman Filter: notes/kalman_filter_1d.ipynb
    - Revenue Cat: notes/revenue_cat.md
    # - The Alignment Problem: notes/alignment_problem.md
    - MKDocs and Github Actions: notes/mkdocs_github_actions.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde



plugins:
  - mkdocs-jupyter:
      include: ["*.py", "*.ipynb"]
      execute: true
      # ignore: ["projects/twitter_sentiment_analysis.ipynb"]
      allow_errors: false
      kernel_name: python3
      theme: dark


