site_name: Peyton Smiths
site_url: ""
use_directory_urls: false

theme:
  # name: material
  nav_style: dark
  pallete:
    # primary: youtube
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs

# Page tree
nav:
#  - 'Peyton Smith Site'
  - About me: index.md
  - Experience: experience.md
  - Projects:
    - Project 1: projects/project1.md
    - Project 2: projects/project2.md
  - Blog: 
    - Blog Post 1: blog/MkdocsGithubActions.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

