site_name: Peyton Smith

theme:
  name: material
  nav_style: dark
  palette:
    scheme: slate
  features:
    - navigation.tabs

# Page tree
nav:
#  - 'Peyton Smith Site'
  - Home: index.md
  - Experience: 
    - Lockheed Martin: experience/lm.md
    - AKW Ventures LLC: experience/akw_ventures.md
    - SEC Directed Internship: experience/sec_directed_internship.md
    - Aggie Sat Lab: experience/aggie_sat_lab.md
  - Projects:
    - Twitter Sentiment Analysis: projects/twitter_sentiment_analysis.ipynb
    - Image Object Detection: projects/em_algorithm.md
    - Kalman Filter: projects/kalman_filter_state_estimate_.ipynb
    - AI player for Xiangqi: projects/dumbo_xiangqi_ai.md
    - Multi Echo and Feedback Comb Filter: projects/multiecho_and_feedback_comb_filter.ipynb
    
    - Eternal Flame: projects/eternal_flame_simulation.md
  - Blog: 
    - Kalman Filter: blog/kalman_filter_1d.ipynb
    - Revenue Cat: blog/revenue_cat.md
    # - The Alignment Problem: blog/alignment_problem.md
    - MKDocs and Github Actions: blog/mkdocs_github_actions.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
- stylesheets/extra.css

plugins:
  - mkdocs-jupyter:
      include: ["*.py", "*.ipynb"]
      execute: true
      # ignore: ["projects/twitter_sentiment_analysis.ipynb"]
      allow_errors: false
      kernel_name: python3
      theme: dark


