site_name: Peyton Smith

theme:
  name: material
  nav_style: dark
  pallete:
    primary: custom
    accent: custom
  features:
    - navigation.tabs

# Page tree
nav:
#  - 'Peyton Smith Site'
  - About me: index.md
  - Experience: experience.md
  - Projects:
    - Project 1: projects/project1.md
    - Project 2: projects/project2.md
  - Blog: 
    - Blog Post 1: blog/MkdocsGithubActions.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde


